### ISSUE TITLE
[feature request] return span informantion on the fly

### ISSUE THREAD

**Issue by IWANABETHATGUY** [MaxXSoft/laps#2]
It is a common usage to report a syntax error or a semantic error at a specific span, it would be better if we can carry the span info at the AST node.

**Comment by MaxXSoft** [comment]
> it would be better if we can carry the span info at the AST node.

This can be done by deriving `Spanned` trait for ASTs, like:

https://github.com/MaxXSoft/laps/blob/3c59c7acb3e9bbda7fcc9846dc672ff09d74727a/examples/clike/main.rs#L255-L260

And then you can get span of the entire AST and report errors about that:

https://github.com/MaxXSoft/laps/blob/3c59c7acb3e9bbda7fcc9846dc672ff09d74727a/examples/clike/main.rs#L635-L638

**Comment by IWANABETHATGUY** [comment]
Thanks
